name: Flux
version: "1.0.28"
slug: flux
description: Flux manages your digital life - all stored locally.
arch:
  - amd64
  - aarch64
startup: services
boot: auto
ingress: true
ingress_port: 3589
panel_icon: mdi:nas
ports:
  3589/tcp: 3589
map:
  - config:rw
  - share:rw
  - media:rw
options:
  data_dir: /config/search_vision
  scan_dirs:
    - /share
    - /media
schema:
  data_dir: str
  scan_dirs:
    - str
privileged:
  - SYS_ADMIN
devices:
  - /dev/fuse
